dataset:
  dat_dir: ''
  frameset_type: avatarrex
  data_device: cpu
  num_workers: 1
  avatarrex_config:
    use_smpl_params: false
    model_type: smplx
    gender: neutral
    smpl_num_pca_comps: 12
    smpl_use_pca: true
    flat_hand_mean: false
    frame_format_digits: 4
    train_frames:
      start_idx: 0
      end_idx: 1
      step_idx: 1
    train_cameras: null
    val_frames:
      start_idx: 0
      end_idx: 1
      step_idx: 1
    val_cameras: null
    test_frames:
      start_idx: 0
      end_idx: 1
      step_idx: 1
    test_cameras: null
model:
  with_mesh_scaling: false
  num_init_samples: 100000
optim:
  lambda_scaling: 1.0
  total_iteration: 30000
  save_every_iter: 1000
  testing_iterations:
  - 1000
  - 3000
  - 5000
  - 10000
  - 20000
  - 30000
  densify_grad_threshold: 0.0002
  min_opacity: 0.001
pipe:
  debug: false
